CREATE TABLE public.TB_CATEGORIA(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	tipo_veiculo VARCHAR(255) NOT NULL,
	veiculo VARCHAR(255) NOT NULL,
)

CREATE TABLE public.TB_PILOTOS(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	sobrenome VARCHAR(255) NOT NULL,
	pais VARCHAR(255) NOT NULL,
	numero INT NOT NULL,
	dt_nascimento DATE NOT NULL,
	equipe varchar(255) NOT NULL,
	ativo BOOLEAN NOT NULL,
	categoria VARCHAR(255) REFERENCES WEBUSER.TB_CATEGORIA(nome)
)

CREATE TABLE public.TB_EQUIPE(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	dt_criacao DATE NOT NULL,
	chefe_equipe VARCHAR(255) NOT NULL,
	num_funcionarios INT NOT NULL,
	categoria VARCHAR(255) REFERENCES WEBUSER.TB_CATEGORIA(nome)
)

CREATE TABLE public.TB_CIRCUITO(
	id SERIAL PRIMARY KEY,
	nome_circuito VARCHAR(255) NOT NULL,
	distancia_volta FLOAT NOT NULL,
	pais VARCHAR(255) NOT NULL,
	num_voltas INTEGER NOT NULL,
	categoria VARCHAR(255) REFERENCES WEBUSER.TB_CATEGORIA(nome)
)